# Generated by Django 4.0.4 on 2022-04-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_postcomment_upvote_response_delete_downvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='response',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
