# Generated by Django 4.0.4 on 2022-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_upvote_response_postcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
