# Generated by Django 4.0.4 on 2022-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userpost_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
