# Generated by Django 4.0.4 on 2022-05-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='tags',
        ),
    ]
